"""Rendering a pull request body.

The body is the incident report plus what was done about it, in trust order, with
the command behind every claim. A reviewer should be able to re-derive any number
in it without asking anyone.

It also has to say what was *not* established. A generated PR that overstates its
own confidence is worse than one that admits a gap: the gap gets discovered later
and at higher cost, and the next generated PR is trusted less than it deserves.
"""

from __future__ import annotations

from typing import Any

from aftermerge.investigator.service import Investigation
from aftermerge.report.render import render

BANNER = (
    "> **Generated by AfterMerge.** Every claim below is backed by a command you can re-run.\n"
    "> Nothing here has been merged, and nothing merges itself."
)


def _strategy_note(strategy: str) -> str:
    if strategy == "revert":
        return (
            "**Strategy: revert.** This restores the previous implementation. It removes the "
            "regression outright, and gives up whatever else the original change was trying to "
            "achieve -- if the change had another purpose, this is not the fix you want."
        )
    return (
        "**Strategy: repair.** This keeps what the original change was trying to achieve and "
        "removes only the pathology. It is a rewrite of your code, so read it as one."
    )


def _limitations(
    investigation: Investigation,
    validation: dict[str, Any],
    request_shapes: int,
    envelope_is_mutating: bool,
) -> list[str]:
    """Only claims the evidence actually supports get made; the rest go here."""
    notes: list[str] = []

    for check in validation.get("checks", []):
        if check.get("status") == "skipped":
            notes.append(f"`{check['name']}` was skipped: {check['detail']}.")

    if request_shapes <= 1:
        notes.append(
            "Exactly one request shape was replayed. Other routes and parameter combinations "
            "were not exercised."
        )
    if not envelope_is_mutating:
        notes.append(
            "The replayed request is read-only, so behaviour under concurrent writes is unverified."
        )

    notes.append(
        "Replay measures database operations and response bodies. It does not establish "
        "correctness under load, nor anything about code paths this request does not reach."
    )
    if not investigation.hypotheses:
        notes.append("No hypothesis was recorded for this incident.")

    return notes


def render_pull_request(
    investigation: Investigation,
    *,
    strategy: str,
    validation: dict[str, Any],
    diffstat: str,
    request_shapes: int = 1,
    envelope_is_mutating: bool = False,
) -> tuple[str, str]:
    """Return the PR title and body."""
    incident = investigation.incident
    title = f"Fix {incident.severity} regression in {incident.service} {incident.route}"

    out: list[str] = [BANNER, "", _strategy_note(strategy), ""]

    out.append("## The change")
    out.append("")
    out.append("```")
    out.append(diffstat.strip() or "(no files changed)")
    out.append("```")
    out.append("")

    out.append("## Validation")
    out.append("")
    out.append("| check | result | detail |")
    out.append("|---|---|---|")
    for check in validation.get("checks", []):
        out.append(f"| `{check['name']}` | {check['status']} | {check['detail']} |")
    out.append("")

    limitations = _limitations(investigation, validation, request_shapes, envelope_is_mutating)
    out.append("## What this does not establish")
    out.append("")
    for note in limitations:
        out.append(f"- {note}")
    out.append("")

    out.append("---")
    out.append("")
    # The full incident report, unchanged, so the PR and the report cannot drift.
    out.append(render(investigation))

    return title, "\n".join(out)
