"""Writing a regression test from an incident's evidence.

Two implementations behind one protocol.

`TemplateGenerator` is deterministic and needs no credentials. It is the default
because the *gate* is what makes a generated test trustworthy, not the thing that
wrote it -- a test is only accepted once it has been shown to fail on the bad
commit and pass on the good one. A template that clears that bar is worth exactly
as much as a model that clears it, and it runs in CI for free.

`AnthropicGenerator` handles the cases a template cannot express. Its client is
injected rather than constructed, so the code path is testable without a key and
without network access.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from typing import Any, Protocol

from aftermerge.testgen.context import TestContext

#: Extra queries per request tolerated before a scaling test fails. Small on
#: purpose: the assertion is "constant", not "roughly constant".
SCALING_ALLOWANCE = 1

#: A page size small enough that an N+1 issues few queries, giving the scaling
#: comparison a meaningful control.
SMALL_PAGE = 5


@dataclass(frozen=True)
class TestCandidate:
    module_name: str
    source: str
    generated_by: str
    rationale: str


class TestGenerator(Protocol):
    name: str
    #: Whether repeated calls return the same source. A deterministic generator
    #: is never retried after a gate rejection: the retry would cost two sandbox
    #: builds and produce the identical file.
    deterministic: bool

    def generate(self, context: TestContext) -> TestCandidate: ...


def _header(context: TestContext) -> str:
    """A docstring citing the measurements that justify the test."""
    site = context.code_site or "the changed code"
    base = f"{context.baseline_version}: {context.baseline_spans_per_request:.1f}"
    cand = f"{context.candidate_version}: {context.candidate_spans_per_request:.1f}"
    return textwrap.dedent(
        f'''\
        """Regression test for {context.service} {context.route}.

        Generated by AfterMerge from incident evidence.

            baseline  {base} db ops/request
            candidate {cand} db ops/request
            amplification: {context.amplification:.1f}x, originating in {site}

        The assertion is on database work, not on latency. The same regression
        measured 11.2x slower against a cold database and 1.45x against a warm
        one, so a timing assertion would be flaky and would have missed it
        entirely under the warm conditions. The operation count was identical in
        both cases.
        """'''
    )


def _render_param(value: str) -> str:
    """Numeric query values are captured as strings; emit them as numbers.

    Cosmetic, but a generated file mixing `limit=5` with `limit='50'` reads as
    careless and invites someone to "fix" it by hand.
    """
    return value if str(value).isdigit() else repr(value)


def _render_query(query: dict[str, str], override: tuple[str, int] | None = None) -> str:
    parts = []
    for key, value in query.items():
        if override is not None and key == override[0]:
            parts.append(f"{key}={override[1]}")
        else:
            parts.append(f"{key}={_render_param(value)}")
    return ", ".join(parts)


def _scaling_test(context: TestContext, param: str, large: int) -> str:
    query_small = _render_query(context.query, override=(param, SMALL_PAGE))
    query_large = _render_query(context.query)

    return textwrap.dedent(
        f'''
        def {context.test_name}(sandbox_under_test):
            """Database work must not grow with the size of the result set."""
            small = replay(
                sandbox_under_test,
                RequestEnvelope.get("{context.path}", {query_small}),
                repeat=REPEAT,
            )
            large = replay(
                sandbox_under_test,
                RequestEnvelope.get("{context.path}", {query_large}),
                repeat=REPEAT,
            )

            assert large.failures == 0 and small.failures == 0, "replay did not complete cleanly"
            assert large.db_spans_per_request <= small.db_spans_per_request + {SCALING_ALLOWANCE}, (
                f"database work scales with {param}: "
                f"{{small.db_spans_per_request:.1f}} operations at {param}={SMALL_PAGE} "
                f"but {{large.db_spans_per_request:.1f}} at {param}={large}. "
                "A query per row is being issued instead of one batched query."
            )
        '''
    ).strip()


def _threshold_test(context: TestContext) -> str:
    query = _render_query(context.query)
    call = (
        f'RequestEnvelope.get("{context.path}", {query})'
        if query
        else f'RequestEnvelope.get("{context.path}")'
    )

    return textwrap.dedent(
        f'''
        def {context.test_name}(sandbox_under_test):
            """Database work per request must stay near the observed baseline."""
            measured = replay(sandbox_under_test, {call}, repeat=REPEAT)

            assert measured.failures == 0, "replay did not complete cleanly"
            assert measured.db_spans_per_request <= {context.threshold}, (
                f"expected at most {context.threshold} database operations per request, "
                f"measured {{measured.db_spans_per_request:.1f}}"
            )
        '''
    ).strip()


class TemplateGenerator:
    """Deterministic generation from measured evidence."""

    name = "template"
    deterministic = True

    def generate(self, context: TestContext) -> TestCandidate:
        size = context.size_parameter

        if size is not None:
            param, large = size
            body = _scaling_test(context, param, large)
            rationale = (
                f"asserts database work is invariant under {param}, which encodes the N+1 "
                "property directly rather than relying on a chosen threshold"
            )
        else:
            body = _threshold_test(context)
            rationale = (
                f"no size-like query parameter found, so the test asserts a threshold of "
                f"{context.threshold} derived from the baseline's "
                f"{context.baseline_spans_per_request:.1f} operations per request"
            )

        source = "\n".join(
            [
                _header(context),
                "",
                "from aftermerge.reproducer.envelope import RequestEnvelope",
                "from aftermerge.reproducer.replay import replay",
                "",
                "REPEAT = 5",
                "",
                "",
                body,
                "",
            ]
        )
        return TestCandidate(
            module_name=context.module_name,
            source=source,
            generated_by=self.name,
            rationale=rationale,
        )


PROMPT = """\
You are writing a single pytest regression test for a production regression that has
already been measured and reproduced. Do not speculate about the cause; the evidence
below is authoritative.

Service: {service}
Route: {route}
Request: {method} {path} params={query}

Measured database operations per request:
  baseline {baseline_version}: {baseline:.1f}
  candidate {candidate_version}: {candidate:.1f}
  originating in: {code_site}

Files changed by the candidate deploy: {changed_files}

Requirements:
- Exactly one test function named {test_name}, taking the `sandbox_under_test` fixture.
- Use `replay(sandbox_under_test, RequestEnvelope.get(path, **params), repeat=5)`, which
  returns an object with `.db_spans_per_request` and `.failures`.
- Assert on database work, never on elapsed time. This regression was only 1.45x slower
  against a warm database, so a latency assertion would miss it.
- The assertion must fail at {candidate:.1f} operations per request and pass at
  {baseline:.1f}. A test that both builds pass is worthless.
- Include a failure message naming both measurements.

Return only the Python module source, with no markdown fences and no commentary.
"""


class AnthropicGenerator:
    """Generation via the Anthropic API, for cases a template cannot express."""

    name = "anthropic"
    deterministic = False

    def __init__(self, client: Any, model: str = "claude-sonnet-5", max_tokens: int = 2000) -> None:
        self._client = client
        self._model = model
        self._max_tokens = max_tokens

    def generate(self, context: TestContext) -> TestCandidate:
        prompt = PROMPT.format(
            service=context.service,
            route=context.route,
            method=context.method,
            path=context.path,
            query=context.query,
            baseline_version=context.baseline_version,
            candidate_version=context.candidate_version,
            baseline=context.baseline_spans_per_request,
            candidate=context.candidate_spans_per_request,
            code_site=context.code_site or "unknown",
            changed_files=", ".join(context.changed_files) or "none recorded",
            test_name=context.test_name,
        )
        response = self._client.messages.create(
            model=self._model,
            max_tokens=self._max_tokens,
            messages=[{"role": "user", "content": prompt}],
        )
        source = "".join(
            block.text for block in response.content if getattr(block, "type", "") == "text"
        ).strip()

        # Models add fences despite being asked not to; stripping them here is
        # cheaper than a retry, and the gate catches anything genuinely broken.
        if source.startswith("```"):
            lines = source.splitlines()
            source = "\n".join(lines[1 : -1 if lines[-1].strip() == "```" else None])

        return TestCandidate(
            module_name=context.module_name,
            source=source.rstrip() + "\n",
            generated_by=f"{self.name}:{self._model}",
            rationale="generated from incident evidence by a language model",
        )
