"""Regression test for orders GET /orders.

Generated by AfterMerge from incident evidence.

    baseline  cbb4790: 2.0 db ops/request
    candidate 8b4fd77: 51.0 db ops/request
    amplification: 25.5x, originating in orders/repository.py

The assertion is on database work, not on latency. The same regression
measured 11.2x slower against a cold database and 1.45x against a warm
one, so a timing assertion would be flaky and would have missed it
entirely under the warm conditions. The operation count was identical in
both cases.
"""

from aftermerge.reproducer.envelope import RequestEnvelope
from aftermerge.reproducer.replay import replay

REPEAT = 5


def test_get_orders_does_not_scale_database_work(sandbox_under_test):
    """Database work must not grow with the size of the result set."""
    small = replay(
        sandbox_under_test,
        RequestEnvelope.get("/orders", limit=5),
        repeat=REPEAT,
    )
    large = replay(
        sandbox_under_test,
        RequestEnvelope.get("/orders", limit=50),
        repeat=REPEAT,
    )

    assert large.failures == 0 and small.failures == 0, "replay did not complete cleanly"
    assert large.db_spans_per_request <= small.db_spans_per_request + 1, (
        f"database work scales with limit: "
        f"{small.db_spans_per_request:.1f} operations at limit=5 "
        f"but {large.db_spans_per_request:.1f} at limit=50. "
        "A query per row is being issued instead of one batched query."
    )
