"""The PR body must not claim more than the evidence supports."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from pathlib import Path

import pytest

from aftermerge.investigator.service import Investigation
from aftermerge.patcher.pullrequest import PullRequestError, gh_command, infer_base
from aftermerge.report.pull_request import render_pull_request
from aftermerge.store.tables import Fact, Hypothesis, Incident

ROOT = Path(__file__).resolve().parents[2]

VALIDATION = {
    "strategy": "revert",
    "summary": "candidate fix c82d515 (revert) passed validation",
    "checks": [
        {"name": "patch_regression_test", "status": "passed", "detail": "passes at c82d515"},
        {"name": "patch_suite", "status": "skipped", "detail": "no suite command configured"},
        {"name": "patch_work_restored", "status": "passed", "detail": "2.0 vs 2.0"},
        {"name": "patch_response_equivalence", "status": "passed", "detail": "identical"},
    ],
}


def investigation(with_hypothesis: bool = True) -> Investigation:
    incident = Incident(
        id=uuid.uuid4(),
        service="orders",
        route="GET /orders",
        baseline_version="cbb4790",
        candidate_version="8b4fd77",
        severity="critical",
        status="open",
        summary="work rose 25.5x",
        onset_at=datetime.now(UTC),
        detected_at=datetime.now(UTC),
    )
    fact = Fact(
        id=uuid.uuid4(),
        incident_id=incident.id,
        kind="db_spans_per_request",
        query_name="span_count_per_trace",
        query_params={},
        raw_result={"columns": [], "rows": []},
        value=51.0,
        unit="spans",
        observed_at=datetime.now(UTC),
    )
    hypotheses = []
    if with_hypothesis:
        hypotheses.append(
            Hypothesis(
                id=uuid.uuid4(),
                incident_id=incident.id,
                statement="commit 8b4fd77 did it",
                kind="change_correlation",
                score=1.0,
                supporting_fact_ids=[fact.id],
                generated_by="test",
                created_at=datetime.now(UTC),
            )
        )
    return Investigation(
        incident=incident, facts=[fact], hypotheses=hypotheses, correlation=None, notes=[]
    )


def body(**overrides) -> str:
    kwargs = dict(strategy="revert", validation=VALIDATION, diffstat="1 file changed")
    kwargs.update(overrides)
    return render_pull_request(investigation(), **kwargs)[1]  # type: ignore[arg-type]


def test_the_body_says_it_was_generated_and_merges_nothing() -> None:
    text = body()
    assert "Generated by AfterMerge" in text
    assert "nothing merges itself" in text


def test_a_revert_is_labelled_as_a_revert() -> None:
    """A reviewer approving a revert is approving the loss of the original intent."""
    text = body(strategy="revert")
    assert "Strategy: revert" in text
    assert "gives up whatever else the original change was trying to achieve" in text


def test_a_repair_is_labelled_as_a_rewrite_of_their_code() -> None:
    text = body(strategy="repair")
    assert "Strategy: repair" in text
    assert "read it as one" in text


def test_skipped_checks_are_surfaced_as_limitations() -> None:
    """A skipped check must not be quietly absorbed into a wall of green."""
    text = body()
    assert "## What this does not establish" in text
    assert "`patch_suite` was skipped" in text


def test_a_single_replayed_shape_is_disclosed() -> None:
    assert "Exactly one request shape was replayed" in body(request_shapes=1)
    assert "Exactly one request shape" not in body(request_shapes=4)


def test_read_only_replay_is_disclosed() -> None:
    assert "concurrent writes is unverified" in body(envelope_is_mutating=False)
    assert "concurrent writes" not in body(envelope_is_mutating=True)


def test_a_missing_hypothesis_is_disclosed() -> None:
    _, text = render_pull_request(
        investigation(with_hypothesis=False),
        strategy="revert",
        validation=VALIDATION,
        diffstat="",
    )
    assert "No hypothesis was recorded" in text


def test_the_full_incident_report_is_embedded() -> None:
    """So the PR and the report cannot drift apart."""
    text = body()
    assert "## Observed facts" in text
    assert "## Verified conclusions" in text


def test_the_title_names_severity_and_route() -> None:
    title, _ = render_pull_request(
        investigation(), strategy="revert", validation=VALIDATION, diffstat=""
    )
    assert title == "Fix critical regression in orders GET /orders"


# --- branch mechanics --------------------------------------------------------


def test_the_base_is_the_branch_that_contains_the_bug() -> None:
    """Not the default branch: the regression lives on its own branch here."""
    assert infer_base("8b4fd77", repo_root=ROOT) == "regression/001-n-plus-one"


def test_aftermerge_fix_branches_are_never_inferred_as_the_base() -> None:
    """They descend from the bad commit, so a naive lookup picks one of them.

    A pull request whose base is its own head has no diff and no reviewer.
    """
    from aftermerge.patcher.pullrequest import FIX_BRANCH_PREFIX

    assert not infer_base("8b4fd77", repo_root=ROOT).startswith(FIX_BRANCH_PREFIX)


def test_an_unreachable_commit_has_no_inferable_base() -> None:
    with pytest.raises(PullRequestError):
        infer_base("0000000", repo_root=ROOT)


def test_the_gh_command_opens_a_draft_and_never_merges() -> None:
    from aftermerge.patcher.pullrequest import FixBranch

    command = gh_command(
        FixBranch(name="aftermerge/fix-x", sha="abc", base="8b4fd77", diffstat=""),
        "main",
        "Fix it",
        Path("/tmp/body.md"),
    )
    assert "--draft" in command
    assert command[:3] == ["gh", "pr", "create"]
    # Not a substring check: every branch name here contains "merge".
    assert "--auto" not in command
    assert "merge" not in command
